// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package disk

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// AreaManagerClient is the client API for AreaManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AreaManagerClient interface {
	Create(ctx context.Context, in *CreateAreaRequest, opts ...grpc.CallOption) (*CreateAreaResponse, error)
	ListUsers(ctx context.Context, in *ListAreaUsersRequest, opts ...grpc.CallOption) (*ListAreaUsersResponse, error)
}

type areaManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewAreaManagerClient(cc grpc.ClientConnInterface) AreaManagerClient {
	return &areaManagerClient{cc}
}

func (c *areaManagerClient) Create(ctx context.Context, in *CreateAreaRequest, opts ...grpc.CallOption) (*CreateAreaResponse, error) {
	out := new(CreateAreaResponse)
	err := c.cc.Invoke(ctx, "/disk.AreaManager/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *areaManagerClient) ListUsers(ctx context.Context, in *ListAreaUsersRequest, opts ...grpc.CallOption) (*ListAreaUsersResponse, error) {
	out := new(ListAreaUsersResponse)
	err := c.cc.Invoke(ctx, "/disk.AreaManager/ListUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AreaManagerServer is the server API for AreaManager service.
// All implementations must embed UnimplementedAreaManagerServer
// for forward compatibility
type AreaManagerServer interface {
	Create(context.Context, *CreateAreaRequest) (*CreateAreaResponse, error)
	ListUsers(context.Context, *ListAreaUsersRequest) (*ListAreaUsersResponse, error)
	mustEmbedUnimplementedAreaManagerServer()
}

// UnimplementedAreaManagerServer must be embedded to have forward compatible implementations.
type UnimplementedAreaManagerServer struct {
}

func (UnimplementedAreaManagerServer) Create(context.Context, *CreateAreaRequest) (*CreateAreaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedAreaManagerServer) ListUsers(context.Context, *ListAreaUsersRequest) (*ListAreaUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedAreaManagerServer) mustEmbedUnimplementedAreaManagerServer() {}

// UnsafeAreaManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AreaManagerServer will
// result in compilation errors.
type UnsafeAreaManagerServer interface {
	mustEmbedUnimplementedAreaManagerServer()
}

func RegisterAreaManagerServer(s *grpc.Server, srv AreaManagerServer) {
	s.RegisterService(&_AreaManager_serviceDesc, srv)
}

func _AreaManager_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAreaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AreaManagerServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/disk.AreaManager/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AreaManagerServer).Create(ctx, req.(*CreateAreaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AreaManager_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAreaUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AreaManagerServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/disk.AreaManager/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AreaManagerServer).ListUsers(ctx, req.(*ListAreaUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AreaManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "disk.AreaManager",
	HandlerType: (*AreaManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _AreaManager_Create_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _AreaManager_ListUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "disk.proto",
}

// UserManagerClient is the client API for UserManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserManagerClient interface {
	Add(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*AddUserResponse, error)
}

type userManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewUserManagerClient(cc grpc.ClientConnInterface) UserManagerClient {
	return &userManagerClient{cc}
}

func (c *userManagerClient) Add(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*AddUserResponse, error) {
	out := new(AddUserResponse)
	err := c.cc.Invoke(ctx, "/disk.UserManager/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserManagerServer is the server API for UserManager service.
// All implementations must embed UnimplementedUserManagerServer
// for forward compatibility
type UserManagerServer interface {
	Add(context.Context, *AddUserRequest) (*AddUserResponse, error)
	mustEmbedUnimplementedUserManagerServer()
}

// UnimplementedUserManagerServer must be embedded to have forward compatible implementations.
type UnimplementedUserManagerServer struct {
}

func (UnimplementedUserManagerServer) Add(context.Context, *AddUserRequest) (*AddUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedUserManagerServer) mustEmbedUnimplementedUserManagerServer() {}

// UnsafeUserManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserManagerServer will
// result in compilation errors.
type UnsafeUserManagerServer interface {
	mustEmbedUnimplementedUserManagerServer()
}

func RegisterUserManagerServer(s *grpc.Server, srv UserManagerServer) {
	s.RegisterService(&_UserManager_serviceDesc, srv)
}

func _UserManager_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagerServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/disk.UserManager/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagerServer).Add(ctx, req.(*AddUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "disk.UserManager",
	HandlerType: (*UserManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _UserManager_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "disk.proto",
}

// ShapeManagerClient is the client API for ShapeManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShapeManagerClient interface {
	Move(ctx context.Context, in *MoveShapeRequest, opts ...grpc.CallOption) (*MoveShapeResponse, error)
}

type shapeManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewShapeManagerClient(cc grpc.ClientConnInterface) ShapeManagerClient {
	return &shapeManagerClient{cc}
}

func (c *shapeManagerClient) Move(ctx context.Context, in *MoveShapeRequest, opts ...grpc.CallOption) (*MoveShapeResponse, error) {
	out := new(MoveShapeResponse)
	err := c.cc.Invoke(ctx, "/disk.ShapeManager/Move", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShapeManagerServer is the server API for ShapeManager service.
// All implementations must embed UnimplementedShapeManagerServer
// for forward compatibility
type ShapeManagerServer interface {
	Move(context.Context, *MoveShapeRequest) (*MoveShapeResponse, error)
	mustEmbedUnimplementedShapeManagerServer()
}

// UnimplementedShapeManagerServer must be embedded to have forward compatible implementations.
type UnimplementedShapeManagerServer struct {
}

func (UnimplementedShapeManagerServer) Move(context.Context, *MoveShapeRequest) (*MoveShapeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Move not implemented")
}
func (UnimplementedShapeManagerServer) mustEmbedUnimplementedShapeManagerServer() {}

// UnsafeShapeManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShapeManagerServer will
// result in compilation errors.
type UnsafeShapeManagerServer interface {
	mustEmbedUnimplementedShapeManagerServer()
}

func RegisterShapeManagerServer(s *grpc.Server, srv ShapeManagerServer) {
	s.RegisterService(&_ShapeManager_serviceDesc, srv)
}

func _ShapeManager_Move_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveShapeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShapeManagerServer).Move(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/disk.ShapeManager/Move",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShapeManagerServer).Move(ctx, req.(*MoveShapeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShapeManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "disk.ShapeManager",
	HandlerType: (*ShapeManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Move",
			Handler:    _ShapeManager_Move_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "disk.proto",
}
